
[I 2023-06-16 08:33:46,928] A new study created in memory with name: no-name-2e65b8f1-2633-4ddf-907a-5b10a958dc88
c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\caiay/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth




100%|██████████| 44.7M/44.7M [00:08<00:00, 5.72MB/s]
[W 2023-06-16 10:17:58,656] Trial 0 failed with parameters: {'learning_rate': 0.0006755055058247345} because of the following error: AttributeError("'float' object has no attribute 'item'").
Traceback (most recent call last):
  File "c:\Users\caiay\AppData\Local\Programs\Python\Python310\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\caiay\AppData\Local\Temp\ipykernel_8416\1008679863.py", line 35, in objective
    accuracy_value = model.validate()[1].item()
AttributeError: 'float' object has no attribute 'item'
[W 2023-06-16 10:17:58,689] Trial 0 failed with value None.